# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - webtest

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout # Checked out your repository
        uses: actions/checkout@v3

      - name: Setup Node # Installs NodeJS 18
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies # Installs your app dependencies
        run: |
          npm install

      - name: 'Login to Azure Subscription' # This is required for OIDC authentication to Azure
        uses: azure/login@v2
        with:
            client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BDB882B3B42541C2A68CFAFC39957325 }}
            tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FA5A85C86D0A43B78EC810BBD1426CDE }}
            subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7E86404A339B4888B2289F9EBE024226 }}
      
      - name: Build Next.js app
        run: |
          npm run build
          mv .next/static .next/standalone/.next/static
          mv public .next/standalone/public
      
      - name: Deploy
        shell: pwsh
        run: |
            $ZIP_FILE_NAME = "./${FILE_NAME}.zip"
            zip $ZIP_FILE_NAME ./* .next -qr

            az webapp deploy `
                --resource-group $RESOURCE_GROUP_NAME `
                --name $WEB_APP_NAME `
                --src-path $ZIP_FILE_NAME `
                --slot staging `
                --type zip `
                --clean true 
        env:
            FILE_NAME: "anyname"
            RESOURCE_GROUP_NAME: "endpt_rg"
            WEB_APP_NAME: "webtest"